# Generated by Django 4.1.2 on 2022-11-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_experience_years_experience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=225)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
            ],
        ),
    ]
