# Generated by Django 4.1.2 on 2022-11-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
