# Generated by Django 4.1.2 on 2022-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
