# Generated by Django 4.1.2 on 2022-11-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duty',
            field=models.TextField(null=True),
        ),
    ]
