# Generated by Django 4.1.2 on 2022-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_experience_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='media'),
        ),
    ]
