# Generated by Django 4.1.2 on 2022-11-22 05:18

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=django_quill.fields.QuillField(default=None, null=True),
        ),
    ]
