# Generated by Django 4.1.2 on 2022-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_job_experience_delete_experience_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='Post', to='blog.category'),
        ),
    ]
